- name: Basic Linux tools set up (Debain, Ubuntu)
  tags: debian,ubuntu,basic,setup
  apt:
    name:
      - tmux
      - python3
      - htop
      - git
      - vim-nox
      - python3-pip
      - python3-virtualenv
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Basic Linux tools set up (Fedora, CentOS, RedHat)
  tags: basic,setup
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - tmux
    - python3
    - vim-nox
    - python3-pip
    - git
    - python3-virtualenv
  when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]


